name: Semgrep SAST

on:
  pull_request:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Semgrep + dependências (HTML)
        run: |
          python -m pip install --upgrade pip
          pip install semgrep jinja2 rich pandas

      - name: Rodar Semgrep (JSON)
        run: |
          semgrep scan --config auto . --json --output resultados.json

      - name: Gerar HTML (a partir do JSON)
        run: |
          python gera_html_semgrep.py

      - name: Publicar artefatos (JSON e HTML)
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-relatorio
          path: |
            resultados.json
            *.html
